declare module 'lucide-react' {
  import * as React from 'react';
  export interface LucideProps extends React.SVGProps<SVGSVGElement> {
    size?: string | number;
    color?: string;
    strokeWidth?: string | number;
    className?: string;
  }
  export type Icon = React.FC<LucideProps>;

  export const Sun: Icon;
  export const Moon: Icon;
  export const Globe: Icon;
  export const Menu: Icon;
  export const X: Icon;
  export const Mail: Icon;
  export const ArrowUp: Icon;
  export const ExternalLink: Icon;
  export const Code: Icon;
  export const Brain: Icon;
  export const BrainCircuit: Icon;
  export const Shield: Icon;
  export const ShieldCheck: Icon;
  export const Award: Icon;
  export const Users: Icon;
  export const Calendar: Icon;
  export const Download: Icon;
  export const CheckCircle: Icon;
  export const CheckCircle2: Icon;
  export const ArrowRight: Icon;
  export const ArrowLeft: Icon;
  export const ArrowDown: Icon;
  export const ArrowUpRight: Icon;
  export const Database: Icon;
  export const Cpu: Icon;
  export const FileText: Icon;
  export const Send: Icon;
  export const Terminal: Icon;
  export const Lock: Icon;
  export const Check: Icon;
  export const Copy: Icon;
  export const FileCheck: Icon;
  export const Sparkles: Icon;
  export const Eye: Icon;
  export const Activity: Icon;
  export const HeartPulse: Icon;
  export const GraduationCap: Icon;
  export const MapPin: Icon;
  export const FolderGit2: Icon;
  export const Layers: Icon;
  export const Briefcase: Icon;
  export const Trophy: Icon;
  export const Star: Icon;
  export const CheckSquare: Icon;
  export const Play: Icon;
  export const RotateCw: Icon;
  export const Info: Icon;
  export const Sliders: Icon;
  export const Fish: Icon;
  export const Server: Icon;
  export const AlertCircle: Icon;
}
